version: 2
updates:
  - package-ecosystem: "github-actions"
    # Look for `.github/workflows` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "monthly"
    groups:
      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"
      minor-and-patch:
        patterns:
        - "*"
        update-types:
        - "patch"
        - "minor"
    cooldown:
      default-days: 7

  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: "monthly"
    groups:
      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"
      minor-and-patch:
        patterns:
        - "*"
        update-types:
        - "patch"
        - "minor"
    cooldown:
      default-days: 7
